name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 0918nobita/setup-cljstyle@v0.1.0
        with:
          cljstyle-version: 0.13.0
      - run: cljstyle version
      - run: cljstyle check
